const test=require('node:test');
const assert=require('node:assert/strict');
const C=require('../game-core.js');
const clone=value=>JSON.parse(JSON.stringify(value));
function start(seed=907,backgroundId='runner'){return C.reduceGame(C.createRun({seed}),{type:'CHOOSE_BACKGROUND',backgroundId})}
function uninterrupted(state){const next=clone(state);next.run.pendingEvent=null;next.run.pendingEncounter=null;next.run.daySummary=null;next.flags.maraIntroResolved=true;next.flags.eliOfferResolved=true;next.flags.earlyThreatResolved=true;next.flags.maraTruthResolved=true;next.flags.courierResolved=true;next.flags.miriOfferResolved=true;next.flags.toneOfferResolved=true;next.flags.midThreatResolved=true;next.flags.baseWatchResolved=true;next.flags.crewCrisisResolved=true;return next}

test('v2 run is seeded, isolated, and starts with background selection',()=>{const a=C.createRun({seed:91}),b=C.createRun({seed:91});assert.deepEqual(a,b);assert.equal(C.VERSION,2);assert.equal(C.SAVE_KEY,'907ogr_v2');assert.equal(a.run.status,'choosing_background');assert.equal(a.lender.balance,620);assert.equal(a.base.name,'North Star Garage')});
test('three backgrounds create distinct valid stat lines',()=>{for(const b of C.BACKGROUNDS){const s=start(9,b.id);assert.equal(s.player.background,b.id);assert.deepEqual(s.player.stats,{aim:b.aim,grit:b.grit,instinct:b.instinct});assert.equal(s.player.cash,b.cash);assert.equal(s.run.status,'playing')}});
test('buy and sell stay inside one market visit',()=>{let s=start();const before=[s.run.day,s.run.slot,s.stats.pipelineAdvances],price=s.world.markets.north_star_lot.prices.weed;s=C.reduceGame(s,{type:'BUY',productId:'weed',qty:2});assert.deepEqual([s.run.day,s.run.slot,s.stats.pipelineAdvances],before);assert.equal(s.player.cash,375-price*2);assert.equal(s.run.currentVisit.trades,1);s=C.reduceGame(s,{type:'SELL',productId:'weed',qty:1});assert.equal(s.stats.pipelineAdvances,0);assert.equal(s.run.currentVisit.trades,2)});
test('locked products cannot trade',()=>{const s=start();const next=C.reduceGame(s,{type:'BUY',productId:'cocaine',qty:1});assert.strictEqual(next,s);assert.equal(s.world.productAccess.cocaine,false)});
test('ending a visit advances exactly once and updates all markets',()=>{let s=uninterrupted(start(22));const before=clone(s.world.markets);s=C.reduceGame(s,{type:'END_MARKET'});assert.equal(s.run.slot,1);assert.equal(s.stats.pipelineAdvances,1);assert.equal(s.stats.marketUpdates,1);for(const a of C.NEIGHBORHOODS){assert.equal(s.world.markets[a.id].updatedAt,1);assert.notDeepEqual(s.world.markets[a.id].prices,before[a.id].prices)}});
test('valid consuming actions invoke the pipeline once',()=>{const cases=[{a:{type:'END_MARKET'}},{a:{type:'LAY_LOW'}},{a:{type:'TRAVEL',neighborhoodId:'downtown'}},{a:{type:'HEAL',amount:20,cost:25},prep:s=>s.player.health=60},{a:{type:'PAY_DEBT',amount:40}},{a:{type:'VISIT_BASE'}},{a:{type:'VISIT_MARA'},prep:s=>{s.people.mara.met=true}},{a:{type:'INVEST_NEIGHBORHOOD',neighborhoodId:'north_star_lot'}}];for(const {a,prep} of cases){let s=uninterrupted(start(500));if(prep)prep(s);const n=C.reduceGame(s,a);assert.equal(n.stats.pipelineAdvances,1,a.type)}});
test('invalid actions invoke the pipeline zero times',()=>{const s=start(40);for(const a of [{type:'TRAVEL',neighborhoodId:'north_star_lot'},{type:'HEAL',amount:20,cost:25},{type:'PAY_DEBT',amount:9999},{type:'UPGRADE_BASE',track:'storage'},{type:'RECRUIT_CREW',crewId:'eli'}]){const n=C.reduceGame(s,a);assert.equal(n.stats.pipelineAdvances,0,a.type)}});
test('four slots roll into next day with summary for every reason',()=>{let s=uninterrupted(start(101));for(let i=0;i<4;i++)s=C.reduceGame(uninterrupted(s),{type:i===1?'LAY_LOW':'END_MARKET'});assert.equal(s.run.day,2);assert.equal(s.run.slot,0);assert.equal(s.stats.pipelineAdvances,4);assert.equal(s.run.daySummary.day,1)});
test('Day 7 Night ends and never exposes Day 8',()=>{let s=uninterrupted(start(1));s.run.day=7;s.run.slot=3;s=C.reduceGame(s,{type:'END_MARKET'});assert.equal(s.run.status,'ended');assert.equal(s.run.day,7);assert.equal(s.run.slot,3);assert.ok(s.run.ending)});
test('net worth includes garage and liquidation but subtracts debt',()=>{const s=start(9),price=s.world.markets.north_star_lot.prices.weed;s.player.inventory.weed.qty=2;s.base.storedInventory.weed.qty=1;s.base.storedCash=40;assert.equal(C.selectors.netWorth(s),s.player.cash+40+price*3-s.lender.balance)});
test('market prices stay bounded over the full clock',()=>{let s=uninterrupted(start(1234));for(let i=0;i<28&&s.run.status==='playing';i++)s=C.reduceGame(uninterrupted(s),{type:'END_MARKET'});for(const a of C.NEIGHBORHOODS)for(const p of C.PRODUCTS){const price=s.world.markets[a.id].prices[p.id];assert.ok(price>=p.min*.72);assert.ok(price<=p.max*1.2)}});
test('neighborhood and product identities remain distinct',()=>{let homeC=0,downC=0,homeM=0,outerM=0;for(let seed=1;seed<=100;seed++){const s=C.createRun({seed});homeC+=s.world.markets.north_star_lot.prices.cocaine;downC+=s.world.markets.downtown.prices.cocaine;homeM+=s.world.markets.north_star_lot.prices.meth;outerM+=s.world.markets.airport_industrial.prices.meth}assert.ok(downC>homeC*1.2);assert.ok(outerM>homeM*1.35)});
test('base visit enables non-advancing storage after one tick',()=>{let s=uninterrupted(start(7));s=C.reduceGame(s,{type:'VISIT_BASE'});assert.equal(s.stats.pipelineAdvances,1);assert.equal(s.base.visiting,true);s.base.tracks.storage=1;const before=s.stats.pipelineAdvances,cash=s.player.cash;s=C.reduceGame(s,{type:'STORE_CASH',amount:100});assert.equal(s.stats.pipelineAdvances,before);assert.equal(s.player.cash,cash-100);assert.equal(s.base.storedCash,100)});
test('each garage upgrade costs one slot and follows track order',()=>{let s=uninterrupted(start(8));s.player.cash=1000;s.base.visiting=true;s=C.reduceGame(s,{type:'UPGRADE_BASE',track:'security'});assert.equal(s.base.tracks.security,1);assert.equal(s.stats.moneySpent.base,140);assert.equal(s.stats.pipelineAdvances,1);s=uninterrupted(s);s.base.visiting=true;s=C.reduceGame(s,{type:'UPGRADE_BASE',track:'security'});assert.equal(s.base.tracks.security,2);assert.equal(s.stats.moneySpent.base,500)});
test('gear purchase equips persistent gear and advances once',()=>{let s=uninterrupted(start(81));s.player.cash=1000;s.base.visiting=true;s=C.reduceGame(s,{type:'BUY_GEAR',gearId:'reliable_handgun'});assert.ok(s.player.gear.owned.includes('reliable_handgun'));assert.equal(s.player.gear.equipped.weapon,'reliable_handgun');assert.equal(s.stats.pipelineAdvances,1)});
test('crew roster caps at two and assignments resolve through pipeline',()=>{let s=uninterrupted(start(88));s.player.cash=2000;s.base.visiting=true;for(const id of ['eli','miri','tone'])s.people.crew[id].introduced=true;s=C.reduceGame(s,{type:'RECRUIT_CREW',crewId:'eli'});s=uninterrupted(s);s.base.visiting=true;s=C.reduceGame(s,{type:'RECRUIT_CREW',crewId:'miri'});s=uninterrupted(s);s.base.visiting=true;const rejected=C.reduceGame(s,{type:'RECRUIT_CREW',crewId:'tone'});assert.equal(C.selectors.recruitedCrew(rejected).length,2);s=C.reduceGame(s,{type:'ASSIGN_CREW',crewId:'miri',assignment:'source_cocaine'});assert.equal(s.people.crew.miri.assignment,null);assert.equal(s.world.productAccess.cocaine,true)});
test('Mara trust and influence are persistent measurable state',()=>{let s=uninterrupted(start(99));s.people.mara.met=true;const cash=s.player.cash;s=C.reduceGame(s,{type:'VISIT_MARA'});assert.equal(s.people.mara.trust,1);assert.equal(s.player.cash,cash-40);s=uninterrupted(s);s.player.cash=200;s=C.reduceGame(s,{type:'INVEST_NEIGHBORHOOD',neighborhoodId:'north_star_lot'});assert.equal(s.world.influence.north_star_lot,1)});
test('story events do not consume a second slot when resolved',()=>{let s=start(107);s=C.reduceGame(s,{type:'END_MARKET'});assert.equal(s.run.pendingEvent.id,'mara_intro');const ticks=s.stats.pipelineAdvances,slot=s.run.slot;s=C.reduceGame(s,{type:'RESOLVE_EVENT',choiceIndex:0});assert.equal(s.stats.pipelineAdvances,ticks);assert.equal(s.run.slot,slot);assert.equal(s.people.mara.met,true)});
test('recent-event control prevents an immediate generic repeat',()=>{let s=uninterrupted(start(119));s.run.recentEvents=['buyer_hurry'];s.player.heat=0;s.world.currentNeighborhoodId='north_star_lot';for(let i=0;i<4;i++){s=C.reduceGame(uninterrupted(s),{type:'END_MARKET'});assert.notEqual(s.run.pendingEvent?.id,'buyer_hurry')}});
test('early confrontation appears by Day 2 and resolving it adds no clock tick',()=>{let s=start(31);for(let i=0;i<6&&!s.run.pendingEncounter;i++){s=C.reduceGame(s,{type:'END_MARKET'});if(s.run.pendingEvent)s=C.reduceGame(s,{type:'RESOLVE_EVENT',choiceIndex:0});if(s.run.daySummary)s=C.reduceGame(s,{type:'DISMISS_DAY_SUMMARY'})}assert.equal(s.run.pendingEncounter.id,'early');const before=s.stats.pipelineAdvances;s=C.reduceGame(s,{type:'RESOLVE_ENCOUNTER',choiceId:'pay'});assert.equal(s.stats.pipelineAdvances,before);assert.equal(s.flags.earlyThreatResolved,true)});
test('encounter results are seeded reproducibly',()=>{function play(){let s=start(222,'enforcer');s.run.pendingEncounter={id:'early',title:'Test',description:'Test',enemyName:'Collector',enemyHealth:24,guard:.08,evasion:.05,pursuit:.1,attack:[5,10],pay:85,step:1,feedback:'Test',finishAfter:false};return C.reduceGame(s,{type:'RESOLVE_ENCOUNTER',choiceId:'fight'})}assert.deepEqual(play(),play())});
test('payoff unlocks a persistent post-debt decision',()=>{let s=uninterrupted(start(65));s.player.cash=1000;s=C.reduceGame(s,{type:'PAY_DEBT',amount:620});assert.equal(s.lender.balance,0);assert.equal(s.lender.afterPayoffOffer,'available');s=uninterrupted(s);s.run.pendingEvent={id:'dre_after_payoff',title:'Door',description:'Door',choices:[{label:'Supplier',effect:{access:'cocaine',lenderTrust:1},result:'Open'}]};s=C.reduceGame(s,{type:'RESOLVE_EVENT',choiceIndex:0});assert.equal(s.world.productAccess.cocaine,true)});
test('final plan creates late encounter and expanded summary',()=>{let s=uninterrupted(start(404));s.run.day=6;s.run.slot=0;s=C.reduceGame(s,{type:'PREPARE_FINAL_PLAN',planId:'escape'});assert.equal(s.run.finalPlan,'escape');s=uninterrupted(s);s.run.day=7;s=C.reduceGame(s,{type:'EXECUTE_FINAL_PLAN'});assert.equal(s.run.pendingEncounter.id,'late');s.people.mara.trust=4;s.run.pendingEncounter.finishAfter=true;s=C.reduceGame(s,{type:'RESOLVE_ENCOUNTER',choiceId:'pay'});assert.equal(s.run.status,'ended');assert.equal(s.run.ending,'mara_escape');const summary=C.selectRunSummary(s);assert.equal(summary.maraStatus,'trusted');assert.ok(Number.isFinite(summary.operationScore))});
