// Static presentation data for events.
//
// ENTITY_REGISTRY drives the in-copy entity tooltips; the UI builds a regex
// from ENTITY_MATCH_ORDER, which is sorted longest-alias-first so "Mina Vale"
// wins over "Mina". Its aliases are also the backward-compatibility surface
// for pre-v1.8 character names.
// AMBIENT_FLAVOR / EVENT_FLAVOR / EVENT_CONTEXT are pure copy banks.
const AMBIENT_FLAVOR = {
  north_star_lot: {
    0: [
      "A bus rattles past on Spenard Road.",
      "Somebody scrapes frost off a windshield with a debit card.",
      "The laundromat sign flickers on, an hour late.",
      "Two crows work over a dropped bag of fries.",
      "A man in a Carhartt jacket counts change on the curb.",
      "Steam off a grate. The smell of somebody else's breakfast.",
      "A truck idles outside the pawn shop with nobody in it.",
      "The light at Thirty-Sixth stays red a long time.",
    ],
    1: [
      "Kids cut through the lot behind the strip mall.",
      "A woman argues into her phone by the ice machine.",
      "Sun comes off the wet asphalt hard enough to squint.",
      "Somebody's car alarm goes off down the block. Nobody flinches.",
      "The barber props his door open with a paint can.",
      "A flatbed rolls by carrying a snowmachine in July.",
      "Two guys shake hands too long outside the check cashing place.",
      "A shopping cart sits upright in the middle of the lot.",
    ],
    2: [
      "Neon comes on above the bar before the sun is done.",
      "A dog barks itself hoarse behind a chain link fence.",
      "Somebody is grilling in a parking space.",
      "The bus shelter glass has a new crack in it.",
      "Music from a passing car, one bar of it, then gone.",
      "A woman waits by the payphone that has not worked in years.",
      "Somebody sweeps the same square of sidewalk twice.",
      "The liquor store door chimes and keeps chiming.",
    ],
    3: [
      "The Night Owl sign hums over an empty lot.",
      "A cab idles at the corner with its light off.",
      "Somebody laughs two blocks over. It carries.",
      "Frost on the hoods already, and it is not even late.",
      "A window upstairs goes dark, then comes back on.",
      "Tires on wet road, going too fast for the corner.",
      "The dumpster lid drops and echoes off the buildings.",
      "Somebody is asleep in a parked car with the engine running.",
    ],
  },
  downtown: {
    0: [
      "Delivery trucks stack up on Fourth Ave.",
      "A tour bus unloads people in brand new rain jackets.",
      "Somebody hoses off the sidewalk in front of a hotel.",
      "Office windows catch the light all the way up.",
      "A street sweeper takes the whole lane and nobody passes it.",
      "Coffee cups in every hand at the crosswalk.",
      "The gift shop rolls its shutter up on carved bears.",
      "Gulls work the trash cans by the transit center.",
    ],
    1: [
      "Construction noise on Fourth. Nothing else pulls.",
      "Suits eat lunch on a low concrete wall.",
      "A guy with a cardboard sign works the light patiently.",
      "Somebody films the mountains with their phone held sideways.",
      "The parking garage gate sticks halfway and somebody swears.",
      "A courier chains a bike to a sign that says no bikes.",
      "Shadows come off the towers and cut the street in half.",
      "Two cops stand talking outside a coffee place, unhurried.",
    ],
    2: [
      "Bar doors open and the noise comes out in a slab.",
      "Somebody in a wedding dress crosses against the light.",
      "The hotel valet stand fills up with idling SUVs.",
      "A busker packs a guitar into a case lined with dollars.",
      "Windows go orange floor by floor as the sun drops.",
      "Somebody hands out flyers nobody takes.",
      "The smell of fryer oil from a place with no sign.",
      "A pedicab driver waits, one foot up on the curb.",
    ],
    3: [
      "Downtown at this hour belongs to the bar crowd.",
      "A squad car rolls slow past the same block twice.",
      "Somebody sits on the curb holding their own shoes.",
      "The transit center is locked and lit and empty.",
      "Glass in the gutter catches the streetlight.",
      "Two guys square up outside a club and then do not.",
      "A cleaner runs a vacuum past a dark lobby window.",
      "The last bus pulls out with three people on it.",
    ],
  },
  airport_industrial: {
    0: [
      "A cargo plane comes in low enough to feel.",
      "Forklifts working somewhere behind a fence.",
      "Frost on the gravel where the trucks have not been yet.",
      "A gate rolls open on a yard full of containers.",
      "Somebody in a vest waves a semi backward.",
      "Diesel and cold air. The road out here has no curb.",
      "A pallet jack squeals across a loading dock.",
      "Two men drink coffee on the bumper of a box truck.",
    ],
    1: [
      "Belly of a jet passes over the service road.",
      "A yard dog barks at every truck and means none of it.",
      "Somebody eats lunch sitting in an open trailer.",
      "Heat shimmer off a hundred yards of parked semis.",
      "The scale house window slides open and shut.",
      "A radio plays country from inside a warehouse.",
      "Tarps snap on a flatbed in the crosswind.",
      "Nothing out here has a sidewalk or needs one.",
    ],
    2: [
      "Sodium lights come on over the freight yards.",
      "A shift lets out and the lot empties in ten minutes.",
      "Somebody chains a gate and tests it twice.",
      "Landing lights stack up in a line toward the runway.",
      "The last truck of the day pulls out heavy.",
      "A security pickup idles with its parking lights on.",
      "Wind comes off the inlet with nothing to stop it.",
      "Cigarette smoke by a door marked no entry.",
    ],
    3: [
      "Between the lights out here, the dark is total.",
      "A conveyor runs somewhere with nobody watching it.",
      "Headlights sweep a fence and keep going.",
      "The cold gets into the gravel and comes back up.",
      "A hangar door stands open on nothing.",
      "Something metal moves in the wind, over and over.",
      "One window lit in a building the size of a block.",
      "The road out is the road in. Nobody is on it.",
    ],
  },
};

const ENTITY_REGISTRY = {
  dre: { id: "dre", name: "Dre", kind: "person", title: "Dre Smooth", aliases: ["Dre Smooth", "Dre"],
    text: "A lender who approaches after you establish yourself. If you accept, $1,200 is due at the run's checkpoint. He names the terms once." },
  yalonda: { id: "yalonda", name: "Yalonda", kind: "person", title: "Yalonda Hernandez", aliases: ["Yalonda Hernandez", "Yalonda"],
    text: "Dominican, early forties, and the landlord of the spare room. The first week is free; every week after is cash." },
  juan: { id: "juan", name: "Juan", kind: "person", title: "Juan Hernandez", aliases: ["Juan Hernandez", "Juan"],
    text: "Yalonda's eighteen-year-old son. He loads a warehouse dock and turns ordinary workplace talk into useful names." },
  mina: { id: "mina", name: "Mina", kind: "person", title: "Mina Vale", aliases: ["Mina Vale", "Mina"],
    text: "Night Owl Mini-Mart clerk in Spenard. She is building an exit into a Ship Creek dispatch job, and public association with your operation would close it." },
  curtis: { id: "curtis", name: "Curtis", kind: "person", title: "Curtis Foyer", aliases: ["Curtis Foyer", "Curtis"],
    text: "Runs the established operation you are growing next to. Concrete exposure builds attention from zero to eight; respect changes what he offers once he notices." },
  goodie: { id: "goodie", name: "Goodie", kind: "person", title: "Goodie", aliases: ["Goodie", "Goodie"],
    text: "Dealer working a corner out of a gym bag at the Wash & Go. He sells once daily, shares reliable rumors with regulars, and never joins the field crew." },
  eli: { id: "eli", name: "Eli", kind: "person", title: "Eli 'Shortcut' Ward", aliases: ["Eli Ward", "Eli"],
    text: "Driver who knows the loading yards, the service roads, and which gates chain up at what hour. Promoted, he places and rotates soldiers for you." },
  pherris: { id: "pherris", name: "Pherris", kind: "person", title: "Pherris Dickens", aliases: ["Pherris Dickens", "Pherris"],
    text: "Connector working an aging Downtown list. She opens buyers and supply, and she prices access in ownership." },
  simone: { id: "simone", name: "Simone", kind: "person", title: "Simone Hart", aliases: ["Simone Hart", "Simone"],
    text: "Anchorage-born former hotel night auditor who built an independent worker-screening and protection network. Respecting her autonomy builds trust; poaching, threats, and leverage raise threat." },
  tone: { id: "tone", name: "Tone", kind: "person", title: "Anton 'Tone' Bell", aliases: ["Anton Bell", "Tone"],
    text: "Former security worker who lost his last job to Curtis's people. He protects the garage and changes how confrontations resolve." },
  deshawn: { id: "deshawn", name: "Deshawn", kind: "person", title: "Deshawn", aliases: ["Deshawn"],
    text: "He put your name in front of Goodie when you were nobody on this block. What your word is worth here runs through him." },
  lena: { id: "lena", name: "Lena", kind: "person", title: "Lena Aguchak", aliases: ["Lena Aguchak", "Lena"],
    text: "Late-forties Yup'ik manager at the Wash & Go. She is saving to turn years of cleaning work into a business of her own." },
  minh: { id: "minh", name: "Minh", kind: "person", title: "Minh Tran", aliases: ["Minh Tran", "Minh"],
    text: "Mid-thirties Vietnamese Alaskan dispatcher. He keeps a local courier route staffed with two phones, paper maps, and exact delivery windows." },
  marcus: { id: "marcus", name: "Marcus", kind: "person", title: "Marcus Bell", aliases: ["Marcus Bell", "Marcus"],
    text: "Early-forties Black Alaskan foreman at Ship Creek Freight. He remembers who arrives before the gate opens and pays at the loading-office door." },
  spenard: { id: "spenard", name: "Spenard", kind: "place", title: "Spenard", aliases: ["Spenard Road", "Spenard"],
    text: "Your home district. The Night Owl, North Star Garage, and the Wash & Go all sit on this stretch, and Curtis watches all three." },
  north_star: { id: "north_star", name: "North Star Garage", kind: "place", title: "North Star Garage", aliases: ["North Star Garage", "North Star"],
    text: "The garage you can lease as a base. It holds stored product and protected cash, and it unlocks crew assignments and safehouse upgrades." },
  night_owl: { id: "night_owl", name: "Night Owl", kind: "place", title: "Night Owl Mini-Mart", aliases: ["Night Owl Mini-Mart", "Night Owl"],
    text: "The corner mini-mart where Mina works and Dre collects. Business done in this lot lands on her shift." },
  wash_go: { id: "wash_go", name: "Wash & Go", kind: "place", title: "The Wash & Go", aliases: ["Wash & Go"],
    text: "Laundromat lot on Spenard Road. Goodie runs the block's nearest supply from it, and the dryer vents are the only warm air on the street." },
  downtown: { id: "downtown", name: "Downtown", kind: "place", title: "Downtown", aliases: ["Downtown"],
    text: "Highest prices and highest police attention. Pherris's list lives here, and so does Curtis's exit lane." },
  ship_creek: { id: "ship_creek", name: "Ship Creek", kind: "place", title: "Ship Creek Freight", aliases: ["Ship Creek"],
    text: "Freight dock hiring dispatch and night unload work. It pays cash the same shift and writes nothing down." },
  industrial: { id: "industrial", name: "Industrial Service Roads", kind: "place", title: "Industrial Service Roads", aliases: ["Industrial Service Roads", "Industrial"],
    text: "Loading bays and unlit service roads by the airport. Cheap weight moves here, and so does everyone who wants to catch you carrying it." },
};

const ENTITY_MATCH_ORDER = Object.values(ENTITY_REGISTRY)
  .flatMap((entity) => entity.aliases.map((alias) => ({ alias, id: entity.id })))
  .sort((a, b) => b.alias.length - a.alias.length);

const EVENT_FLAVOR = {
  mina_intro: "The heater clicks louder than the drink cooler. You study the coffee machine without pretending you know the routine. She watched from behind the register a little longer than professionalism requires.",
  eli_offer: "He waits outside the garage with an impound notice folded into his jacket, the crease worn soft from being taken out and put back. He has clearly rehearsed that last sentence.",
  eli_callback: "He comes up beside the garage without knocking, which is new. He wanted you to hear about the other driver from him first. Repeating his terms word for word is how he shows the price has not moved.",
  pherris_offer: "She took the corner booth Downtown before you arrived and ordered for both of you, which tells you how the conversation is going to go.",
  tone_offer: "He stands under the broken security light, far enough back that he is out of the doorway. He leaves the part about Curtis for last.",
  tone_recruit: "He waited by the door this time instead of the light, which is a different kind of standing there. The number has not moved since the first conversation.",
  pherris_recruit: "She did not ask where you would be, and she is there anyway, which is the whole demonstration. Everything she says next she already knew before you sat down.",
  deshawn_offer: "He was already at the counter when you came in, which means he knew your evening better than you did. The coffee in front of him is still full.",
  mina_shift_change: "The heater ticks over the door. The owner drinks his coffee here every Thursday and knows every face on this block. On this street a name is the first thing anyone trades.",
  mina_invitation: "She is outside when you come around the corner, coat already on. The lot's sodium light makes the slush look orange. She is asking what you can build in four hours, on foot, in Spenard.",
  mina_boundary: "She meets you behind the store with the keys already in her hand and the lights already off. \"I am not asking you to fix it,\" she says first. She wants enough information to decide for herself.",
  courier: "He is conscious and saying nothing at all. Drivers who slow down instead of speeding up have already been told where to stop.",
  dre_after_payoff: "He counts the final stack across the hood and it comes out right. Staying afterward is new. He lays the options out like a man reading from a menu he wrote himself.",
  base_watch: "In this weather a running engine means somebody is sitting in the car rather than watching from somewhere warm. Being obvious appears to be the point of it.",
  crew_crisis: "The message carries no name, no explanation, and no request. The phone vibrates itself half off the garage table. Six is when the booking desk changes hands and the price of quiet goes up.",
  buyer_hurry: "The hurry is his. Two customers wait by the door for the cigarette line to clear. This is Mina's lot, and her shift is the reason anyone here recognizes you.",
  checkpoint: "Orange cones and a tow truck sit at the head of the lane. The officer looks inside nothing. He taps, moves on, and taps the next one.",
  curtis_cut: "The angle of the car is deliberate. He is unhurried about all of it, and the line of vehicles behind you does the pressuring for him.",
  rough_night: "They let the arithmetic happen on its own, which is most of the work. Silence costs them nothing and buys them the first move.",
  dre_warning: "He parks with the engine off and hurries neither count. He never comments on the amount. Handing money back is worse than being short, and he knows it.",
  eli_missed_turn: "He took a lap around the freight yard before circling back in from the other side. He is watching your face to learn whether you want a driver who thinks.",
  eli_service_map: "It is drawn to no scale at all and it beats anything you could buy. The two crossings appear on no map because they are technically somebody's parking lot. He has never shown it to anyone.",
  eli_last_run: "He asks it in the middle of a conversation about fuel prices, the way people ask questions they have been carrying around. He would rather find out now than in eight days.",
  dre_terms: "The meeting is already arranged, and Dre still makes you read the paper again. \"People make it complicated after. Not me.\"",
  dre_first_payment: "The back light is out again, so he counts by the glow of the open car door. He takes his time, and he keeps whatever he decided while counting.",
  curtis_mark: "Same wall, same spot, different hand. Whatever the tag says now, it is not what it said on Monday. Nobody has spoken to you directly, which is how this stage of Curtis's attention works.",
  curtis_tax: "He is unhurried and entirely unthreatening, and he stands close enough that the two people at the corner hear none of the words. A number set low is a number set to end the argument early.",
  goodie_corner_intro: "The vents push warm lint-smelling air across the lot, the only warm thing on this stretch of road. Lifting his chin instead of looking away is an opening he can still take back.",
  goodie_recognized: "Four people have already given him their version. He wants yours from you. Calm is worse than angry, because calm means he has already finished the arithmetic.",
  wet_bricks: "He is not the man who packed it. The seals look intact. Some of them look intact. He will not be here tomorrow to discuss the difference.",
  door_knock: "A plow berm blocks the walk behind the second officer, so the stairs are the only way down. Whatever is in the unit with you is on a clock now.",
  stranded_wagon: "The hood has been up long enough that she has stopped expecting anything. She waves the way people wave after forty cars have already gone past.",
  found_phone: "Face-down, still warm, left in a hurry at the transit shelter on Fourth Avenue. Six days of somebody's schedule sits in your hand, and somebody wants it back before you finish reading.",
  careful_customer: "Nobody else in the line looks at either of you, which is its own kind of information. People who buy here watch a sale happen. These people watch something else.",
  dock_shift: "He stands in the door light while the wind comes up the channel hard enough to swing the sodium lamps on their arms. It is honest work, and it pays the way honest work pays.",
  garage_furnace: "The answering machine on the sticker does not say when anyone calls back. Six hours of Anchorage winter against a cold wall decides how much of the stock still sells.",
  sedan_rumor: "The story reaches you third-hand and improves on the way. The person telling you did not see it. The person who told them did not see it either.",
  midtown_lights: "The queue crawls at ten miles an hour on the Seward Highway at Thirty-Sixth. A collision closes lanes and gathers uniforms in one place for an hour at a time.",
  eli_lieutenant_offer: "He leans against the bay door while he says it. \"Routes are fine\" is his opening line, which is how he tells you he has outgrown them.",
  spenard_block_scouted: "The dates matter more than the circles. Three colors of ink mean three passes on foot, at different hours, across more than one week.",
  curtis_respect_notice: "The word reaches you secondhand, the way it always does. Respect and pressure are separate accounts with Curtis, and this one just moved.",
  soldier_raid_aftermath: "The regular buyers work it out on the spot, on the sidewalk, in front of each other. That decision gets made once and then it holds.",
};

const EVENT_CONTEXT = {
  mina_intro: { who: "Mina Vale, the Night Owl clerk meeting you for the first time", where: "Night Owl Mini-Mart, Spenard", stakes: "Choose the tone of a first conversation with someone who has no prior history with you." },
  eli_offer: { who: "Eli Ward, a local driver looking for work", where: "Outside North Star Garage, Spenard", stakes: "Decide whether Eli gets a test route, only shares road information, or remembers being turned away." },
  eli_callback: { who: "Eli Ward, still working the service roads", where: "North Star Garage, Spenard", stakes: "Reopen the door to a test route or confirm that Eli should look elsewhere." },
  pherris_offer: { who: "Pherris Dickens, a connected supplier", where: "Downtown corner booth", stakes: "Supplier access, loyalty, and how much ownership you are willing to share." },
  pherris_recruit: { who: "Pherris Dickens, who has been counting your money from a distance", where: "Wherever you were already working", stakes: "A contact list, better Downtown prices, a wage every night, and someone who expects to be told things first." },
  tone_offer: { who: "Anton Bell, a former security worker", where: "North Star Garage", stakes: "Protection against Curtis at the cost of another wage." },
  tone_recruit: { who: "Anton Bell, back with a plate number and a price", where: "North Star Garage", stakes: "A body at the door, a wage every night, and how confrontations end from here." },
  deshawn_offer: { who: "Deshawn, the block's quiet fixer", where: "The Night Owl, Spenard", stakes: "A first crew member: de-escalation, introductions, and a wage every day." },
  mina_shift_change: { who: "Mina Vale, twenty minutes past close", where: "Night Owl Mini-Mart, Spenard", stakes: "Mina is building an exit that public association with your operation would close. How much you tell her sets the terms." },
  mina_invitation: { who: "Mina, off shift early and without a car", where: "The Night Owl lot, Spenard", stakes: "Four hours away from the block, or four hours she spends near your operation. Both cost time." },
  mina_boundary: { who: "Mina and the question a customer left behind", where: "Behind the Night Owl after closing", stakes: "Her job, her consent, and whether she gets to decide with accurate information." },
  mina_after: { who: "Mina, at the end of your week and the start of hers", where: "Night Owl Mini-Mart, Spenard", stakes: "What the week cost her, and what is left to say about it." },
  eli_missed_turn: { who: "Eli Ward, back an hour later than the route allows", where: "North Star Garage, Spenard", stakes: "Whether you want a driver who thinks, or one who does what the clock says." },
  eli_service_map: { who: "Eli and a map he drew himself", where: "Passenger seat outside North Star Garage", stakes: "Route knowledge nobody else on this block has, and what he wants for it." },
  eli_last_run: { who: "Eli, asking a rehearsed question", where: "North Star Garage, Spenard", stakes: "Whether the operation has a place for him after the checkpoint." },
  dre_terms: { who: "Dre Smooth and one folded sheet of paper", where: "Behind the Night Owl Mini-Mart", stakes: "The amount, the date, and what he expects between now and then." },
  dre_first_payment: { who: "Dre, counting the first money you have brought him", where: "Behind the Night Owl Mini-Mart", stakes: "The shape of the rest of the week's arrangement." },
  dre_due_day: { who: "Dre on the day the note comes due", where: "Behind the Night Owl Mini-Mart", stakes: "What happens to the balance, and to his patience." },
  dre_day7: { who: "Dre, closing the week's account", where: "Behind the Night Owl Mini-Mart", stakes: "What your name is worth to him after seven days." },
  curtis_mark: { who: "Curtis's people, working through somebody else", where: "Your usual corner", stakes: "Confirmation that you are being watched, and by whom." },
  curtis_tax: { who: "Curtis Foyer, in person, which is the message", where: "The Downtown exit lane", stakes: "A cut, a favor, or a public no." },
  curtis_day7: { who: "Curtis, deciding what you were", where: "Wherever he finds you at the checkpoint", stakes: "Whether the pressure phase ends as a partnership, a truce, or a problem." },
  goodie_corner_intro: { who: "Goodie, running a corner out of a gym bag", where: "The Wash & Go lot, Spenard Road", stakes: "Whether the block's nearest supply becomes a contact, a mark, or neither." },
  goodie_recognized: { who: "Deshawn, who vouched for you before you robbed Goodie", where: "Outside the Wash & Go, Spenard", stakes: "What your word is worth on the block after you spent it." },
  wet_bricks: { who: "A driver unstrapping someone else's mistake", where: "Loading Bay Seven, Industrial Service Roads", stakes: "Cheap weight of unverified condition, and a seller who will not be here tomorrow." },
  door_knock: { who: "Two APD officers working the row", where: "The fourplex two doors from North Star Garage", stakes: "What is in the unit with you, and how long the knocking takes to reach this door." },
  stranded_wagon: { who: "A woman with two kids and a dead battery", where: "The Minnesota Drive off-ramp shoulder", stakes: "Twenty minutes of your week against a stranger's night." },
  found_phone: { who: "Whoever left it, and whoever keeps calling it", where: "The transit shelter on Fourth Avenue", stakes: "Six days of somebody's pickup schedule, and whether you take it." },
  careful_customer: { who: "A buyer asking better questions than he should", where: "The corner you are standing on", stakes: "One sale, and who hears about it afterward." },
  dock_shift: { who: "A foreman short two people on a night unload", where: "Ship Creek freight dock", stakes: "Four hours you do not have, for money nobody writes down." },
  garage_furnace: { who: "The garage, and everything stored along the cold wall", where: "North Star Garage, back bay", stakes: "A repair bill, an afternoon, or whatever six hours of outside temperature did to the stock." },
  sedan_rumor: { who: "Somebody's cousin, two conversations removed", where: "Wherever you happened to be standing", stakes: "A story nobody has confirmed, and what you are willing to spend on it." },
  midtown_lights: { who: "Four cruisers and a closed left lane", where: "The Seward Highway at Thirty-Sixth", stakes: "Half a mile at walking speed in front of every officer in Midtown." },
  courier: { who: "An injured courier and approaching drivers", where: "Industrial Service Roads, Bay Twelve", stakes: "Cash, Heat, and who controls the courier's route information." },
  dre_after_payoff: { who: "Dre Smooth", where: "Behind the Mini-Mart", stakes: "A new debt, premium supply access, or independence." },
  base_watch: { who: "Curtis's watcher and a possible plainclothes officer", where: "Across from North Star Garage", stakes: "Your stored operation and whether the watcher identifies its value." },
  crew_crisis: { who: "A jailed crew member and APD", where: "North Star Garage burner line", stakes: "$180 or the loyalty of everyone working for you." },
  buyer_hurry: { who: "A hurried buyer, Mina, and an observer", where: "Mini-Mart parking lot", stakes: "Fast cash against Heat and exposure near Mina's job." },
  checkpoint: { who: "APD officers and a tow driver", where: "Airport service road", stakes: "$90 or a risky inspection of your vehicle and cargo." },
  curtis_cut: { who: "Curtis's driver", where: "Downtown exit lane", stakes: "$120, physical injury, and Curtis's respect." },
  rough_night: { who: "Three people tied to Curtis", where: "Industrial Bay Nine", stakes: "$80 or a dangerous attempt to hold your ground." },
  dre_warning: { who: "Dre Smooth", where: "Behind the Mini-Mart", stakes: "Dre's patience and the pressure attached to the unpaid balance." },
  eli_lieutenant_offer: { who: "Eli Ward, with a second phone in his jacket", where: "North Star Garage, Spenard", stakes: "Whether Eli starts running soldiers and corners instead of only routes." },
  spenard_block_scouted: { who: "Eli, with a hand-marked map of Spenard", where: "North Star Garage, Spenard", stakes: "Counted numbers on every block, in place of a guess." },
  curtis_respect_notice: { who: "Word from two blocks over", where: "Spenard", stakes: "What Curtis thinks of an operation that is starting to look like his." },
  soldier_raid_aftermath: { who: "The block, the morning after", where: "Spenard", stakes: "Nothing to decide here. Just what it cost." },
};

module.exports = {
  AMBIENT_FLAVOR,
  ENTITY_REGISTRY,
  ENTITY_MATCH_ORDER,
  EVENT_FLAVOR,
  EVENT_CONTEXT,
};
